Added Readme and removed unused code.
mlopstemplates/aml_configure pull request #7
Opened 2020-06-29 06:13 UTC by vivishno

Added Files-
-readme.md
-Security.md
-CODE_OF_CONDUCT.md
-LICENSE.md

Removed unused code.

2020-06-29 08:42 UTC, ashishonce requested changes

2020-06-29 08:42 UTC, ashishonce commented on .github/workflows/test.yml
> +          resource_group: "PythonSdk"
this won't work as account is mine

2020-06-29 11:14 UTC, vivishno commented on .github/workflows/test.yml
> +          resource_group: "PythonSdk"
updated

2020-06-30 10:07 UTC, ashishonce approved these changes

2020-06-30 10:07 UTC, merged